import React, { useState } from 'react';

import { FileText, TrendingUp, User, Clock, Code, Copy, Check, Lightbulb, ExternalLink } from 'lucide-react';

// Custom SVG Github icon since brand logos were removed from Lucide-react v4
function GithubIcon({ size = 12, ...props }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      stroke="currentColor"
      strokeWidth="2.2"
      fill="none"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  );
}

// Maps our AI & fallback categories to high-end Tailwind badge colors dynamically
const categoryStyles = {
  security: 'bg-red-500/10 text-red-700 dark:text-red-400 border border-red-500/20',
  performance: 'bg-yellow-500/10 text-yellow-750 dark:text-yellow-400 border border-yellow-500/20',
  maintenance: 'bg-blue-500/10 text-blue-700 dark:text-blue-400 border border-blue-500/20',
  feature: 'bg-purple-500/10 text-purple-700 dark:text-purple-400 border border-purple-500/20',
  fixme: 'bg-red-500/10 text-red-700 dark:text-red-400 border border-red-500/20',
  hack: 'bg-yellow-500/10 text-yellow-750 dark:text-yellow-400 border border-yellow-500/20',
  todo: 'bg-blue-500/10 text-blue-700 dark:text-blue-400 border border-blue-500/20',
};

/**
 * DEBTCARD PRESENTATIONAL COMPONENT
 * Renders metadata, age, and code coordinates with custom animations and high-contrast texts.
 */
export function DebtCard({ item, repoUrl }) {
  const isHighRisk = item.riskScore >= 7;
  const [showFix, setShowFix] = useState(false);
  const [copied, setCopied] = useState(false);
  const [copiedJira, setCopiedJira] = useState(false);

  const handleCopyJira = (e) => {
    e.stopPropagation();
    // Format details using Jira Wiki markup syntax
    const jiraWikiText = `h3. ⚠️ Technical Debt Finding: ${item.category}
* *File:* ${item.file} (Line ${item.line})
* *Severity:* ${item.riskScore}/10
* *Author:* ${item.author || 'Unknown'}
h3. 💡 AI Analysis & Impact
{quote}
${item.explanation}
{quote}
h3. 🛠️ Suggested Code Fix
{code:javascript}
${item.fixSuggestion || '// No fix suggested.'}
{code}
---
_Generated by Automated Tech-Debt Auditor_`;
    navigator.clipboard.writeText(jiraWikiText);
    setCopiedJira(true);
    setTimeout(() => setCopiedJira(false), 2000);
  };

  const [copiedLinear, setCopiedLinear] = useState(false);

  // 1. Copies ticket details formatted in standard Markdown (for Linear, GitLab, etc.)
  const handleCopyLinear = (e) => {
    e.stopPropagation();
    const linearMarkdown = `### ⚠️ Technical Debt Finding: ${item.category}
- **File:** \`${item.file}\` (Line ${item.line})
- **Severity:** ${item.riskScore}/10
- **Author:** ${item.author || 'Unknown'}

#### 💡 AI Analysis & Impact
${item.explanation}

#### 🛠️ Suggested Code Fix
\`\`\`javascript
${item.fixSuggestion || '// No fix suggested.'}
\`\`\`

---
*Generated by Automated Tech-Debt Auditor*`;

    navigator.clipboard.writeText(linearMarkdown);
    setCopiedLinear(true);
    setTimeout(() => setCopiedLinear(false), 2000);
  };

  // 2. Generates pre-filled GitHub New Issue link
  const getGitHubIssuesUrl = () => {
    if (!repoUrl) return null;
    let cleanUrl = repoUrl.trim().replace(/\.git$/, '');
    if (!cleanUrl.startsWith('https://')) {
      cleanUrl = 'https://' + cleanUrl.replace(/.*github\.com/, 'github.com');
    }
    if (!cleanUrl.includes('github.com')) return null;

    const title = encodeURIComponent(`[Tech Debt] Fix: ${item.comment.slice(0, 50)}${item.comment.length > 50 ? '...' : ''}`);
    const body = encodeURIComponent(`### Technical Debt Details
- **Type:** ${item.category}
- **File:** \`${item.file}\` (Line ${item.line})
- **Severity:** ${item.riskScore}/10
- **Line Author:** ${item.author || 'Unknown'}

### AI Impact Analysis
${item.explanation}

### Suggested Code Fix
\`\`\`javascript
${item.fixSuggestion || '// No fix suggested.'}
\`\`\`

---
*Generated by [Automated Tech-Debt Auditor](https://github.com/Adityuh1/TECH-DEBT-auditor)*`);

    return `${cleanUrl}/issues/new?title=${title}&body=${body}&labels=tech-debt`;
  };

  const gitHubIssueUrl = getGitHubIssuesUrl();
  // Calculate how long this debt item has existed
  const createdDate = new Date(item.createdAt);
  const today = new Date();
  const diffTime = Math.abs(today - createdDate);
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

  // Clean up the category key for lookup (e.g. "Security" -> "security")
  const catKey = (item.category || 'todo').toLowerCase();
  const badgeStyle = categoryStyles[catKey] || 'bg-zinc-150 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400 border border-zinc-350 dark:border-zinc-700/50';

  const handleCopy = (e) => {
    e.stopPropagation();
    navigator.clipboard.writeText(item.fixSuggestion);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className={`flex flex-col justify-between bg-white dark:bg-zinc-900/40 border border-zinc-200 dark:border-zinc-800/80 p-6 rounded-xl min-h-[270px] box-border transition-all duration-300 ${isHighRisk
      ? 'border-t-4 border-t-red-500 hover:border-red-500/30 hover:-translate-y-1 hover:shadow-lg'
      : 'border-t-4 border-t-indigo-500 dark:border-t-indigo-400 hover:border-indigo-500/30 hover:-translate-y-1 hover:shadow-lg'
      }`}>

      {/* Upper Content Segment */}
      <div className="mb-6">

        {/* Card Header: Category & Score */}
        <div className="flex justify-between items-center mb-3">
          <span className={`text-[15px] font-extrabold uppercase tracking-wider px-2.5 py-0.5 rounded-md ${badgeStyle}`}>
            {item.category}
          </span>
          <span className={`text-xs font-bold flex items-center gap-1 ${isHighRisk ? 'text-red-650 dark:text-red-400' : 'text-indigo-650 dark:text-indigo-400'
            }`}>
            <TrendingUp size={14} /> Score: {item.riskScore}
          </span>
        </div>

        {/* Comment and AI explanation */}
        <p className="text-zinc-900 dark:text-zinc-100 font-bold mb-2 text-left italic leading-relaxed text-sm">
          "{item.comment}"
        </p>
        <p className="text-xs text-zinc-650 dark:text-zinc-400 text-left leading-relaxed">
          {item.explanation}
        </p>

        {/* Collapsible Suggestion Drawer */}
        {item.fixSuggestion && (
          <div className="mt-4 text-left">
            <button
              onClick={() => setShowFix(!showFix)}
              className="flex items-center gap-1 text-[11px] font-bold text-indigo-650 dark:text-indigo-400 hover:text-indigo-850 dark:hover:text-indigo-300 transition-colors cursor-pointer"
            >
              <Lightbulb size={12} className="shrink-0" />
              <span>{showFix ? 'Hide Suggested Fix' : '💡 View Suggested Fix'}</span>
            </button>

            {showFix && (
              <div className="relative mt-2.5 p-3 bg-zinc-55 dark:bg-zinc-950/70 border border-zinc-200 dark:border-zinc-850 rounded-xl text-left shadow-inner">
                <button
                  onClick={handleCopy}
                  className="absolute top-2 right-2 p-1.5 bg-white dark:bg-zinc-900 border border-zinc-250 dark:border-zinc-800 hover:border-zinc-350 dark:hover:border-zinc-700 text-zinc-500 dark:text-zinc-400 rounded-lg transition-all cursor-pointer shadow-sm"
                  title="Copy code to clipboard"
                >
                  {copied ? <Check size={11} className="text-green-600 dark:text-green-500" /> : <Copy size={11} />}
                </button>
                <pre className="text-[10px] font-mono text-zinc-700 dark:text-zinc-300 overflow-x-auto whitespace-pre-wrap pr-8 leading-relaxed">
                  <code>{item.fixSuggestion}</code>
                </pre>

              </div>
            )}
          </div>
        )}
      </div>

      {/* Bottom Metadata Panel */}
      <div className="border-t border-zinc-200/50 dark:border-zinc-800/40 pt-4 mt-auto">

        {/* Author & Age block */}
        <div className="flex justify-between text-[11px] text-zinc-500 dark:text-zinc-450 bg-zinc-50 dark:bg-zinc-950/20 px-3 py-2 rounded-lg border border-zinc-200 dark:border-zinc-850/30 mb-2">
          <div className="flex items-center gap-1.5">
            <User size={12} className="text-zinc-450 dark:text-zinc-500" />
            <span>Author: <span className="font-bold text-zinc-700 dark:text-zinc-300">{item.author || 'Unknown'}</span></span>
          </div>
          <div className="flex items-center gap-1.5">
            <Clock size={12} className="text-yellow-600 dark:text-yellow-500/70" />
            <span className="font-bold text-yellow-600 dark:text-yellow-500/80">{diffDays} days old</span>
          </div>
        </div>

        {/* Technical Code Coordinates & Ticketing Actions */}
        <div className="flex flex-col gap-2">
          {/* Coordinates Tag */}
          <div className="text-[10px] text-zinc-500 dark:text-zinc-450 font-mono bg-zinc-55 dark:bg-zinc-950/40 px-3 py-2 rounded-lg border border-zinc-200 dark:border-zinc-850/60 flex items-center gap-1.5 truncate">
            <Code size={12} className="text-indigo-600 dark:text-indigo-400/80 shrink-0" />
            <span className="truncate" title={`${item.file} : Line ${item.line}`}>
              {item.file} <span className="text-indigo-650 dark:text-indigo-400/60">: L{item.line}</span>
            </span>
          </div>

          {/* Ticket Row */}
          <div className="flex gap-2 items-center justify-between">
            <span className="text-[10px] font-bold uppercase tracking-wider text-zinc-450 dark:text-zinc-500">
              Create Ticket:
            </span>
            <div className="flex gap-1.5 items-center">
              {/* GitHub Issue Button (if repo is hosted on GitHub) */}
              {gitHubIssueUrl && (
                <a
                  href={gitHubIssueUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  onClick={(e) => e.stopPropagation()}
                  className="p-2 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 text-zinc-650 dark:text-zinc-450 hover:border-zinc-350 dark:hover:border-zinc-700 hover:text-zinc-800 dark:hover:text-zinc-300 text-[11px] font-bold rounded-lg transition-all flex items-center gap-1 shadow-sm"
                  title="Create pre-filled GitHub Issue"
                >
                  <GithubIcon size={12} />
                  <span>GH Issue</span>
                </a>
              )}

              {/* Jira Copy Button */}
              <button
                onClick={handleCopyJira}
                className={`p-2 border text-[11px] font-bold rounded-lg transition-all cursor-pointer flex items-center gap-1 shadow-sm ${
                  copiedJira
                    ? 'bg-green-500/10 border-green-500/30 text-green-600 dark:text-green-400'
                    : 'bg-white dark:bg-zinc-900 border-zinc-200 dark:border-zinc-800 text-zinc-650 dark:text-zinc-450 hover:border-zinc-350 dark:hover:border-zinc-700 hover:text-zinc-800 dark:hover:text-zinc-300'
                }`}
                title="Copy Jira Wiki Description"
              >
                {copiedJira ? <Check size={12} /> : <FileText size={12} />}
                <span>Jira</span>
              </button>

              {/* Linear Copy Button */}
              <button
                onClick={handleCopyLinear}
                className={`p-2 border text-[11px] font-bold rounded-lg transition-all cursor-pointer flex items-center gap-1 shadow-sm ${
                  copiedLinear
                    ? 'bg-green-500/10 border-green-500/30 text-green-600 dark:text-green-400'
                    : 'bg-white dark:bg-zinc-900 border-zinc-200 dark:border-zinc-800 text-zinc-650 dark:text-zinc-450 hover:border-zinc-350 dark:hover:border-zinc-700 hover:text-zinc-800 dark:hover:text-zinc-305'
                }`}
                title="Copy Linear Markdown Template"
              >
                {copiedLinear ? <Check size={12} /> : <Copy size={12} />}
                <span>Linear</span>
              </button>
            </div>
          </div>
        </div>

      </div>

    </div>
  );
}
